### ISSUE TITLE
Publish a Storybook v3 compatible version

### ISSUE THREAD

**Issue by elisherer** [storybooks/storybook-addon-a11y#7]
Since storybook changed its libraries names,
A replace of lib names is required:
`@kadira/storybook` -> `@storybook/react`
`@kadira/storybook-addons` -> `@storybook/addons`

**Comment by jbovenschen** [comment]
@jrwebdev can you maybe make a PR which makes this package storybook v3 compatible.

Also we are currently migrating this package to the storybook repo, maintenance will be done by the storybook team.

**Comment by jrwebdev** [comment]
@jbovenschen I'm having some issues with it not being able to retrieve a channel (via `addons.getChannel()`) when I upgraded to v3. My best guess is that it's because the `@storybook/react` package is bringing in `@storybook/addons` too despite it being in the package's peer deps and therefore the a11y addon is using a different instance of the AddonStore class. 

Not sure I'll have much time to look into this further, so if you're planning on moving the package to the monorepo it may be best just to resolve the issue there.

**Comment by jrwebdev** [comment]
@jbovenschen ignore the above - I was being tripped up by `npm link`! I've created a PR.

**Comment by jbovenschen** [comment]
Thank you for doing so. Will wait for someone of the storybook team to merge it, because it is not my repo anymore.

**Comment by ndelangen** [comment]
DONE! 🎉 

`storybook-addon-a11y@3.0.0`

**Comment by ndelangen** [comment]
I updated to use `prop-types` and any version of react.
